# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [];

  boot = {
    # Do `nixos-generate-config --show-hardware-config`
    # to see what should be here
    kernelModules = [ ];
    extraModulePackages = [ ];

    initrd = {
      availableKernelModules = [];
      kernelModules = [ ];
    };

    loader = {
      efi.canTouchEfiVariables = true;
      grub = {
        enable = true;
        version = 2;
        device = "/dev/sda";
      };
      # systemd-boot.enable = true;
    };
  };

  virtualisation.virtualbox.guest.enable = true;

  swapDevices = [ ];

  # Enable sound.
  sound.enable = true;
  hardware = {
    pulseaudio.enable = true;
    enableRedistributableFirmware = true;
    # cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
